### ISSUE TITLE
关于“条件替换”

### ISSUE THREAD

**Issue by DLslime** [GWYOG/LocalizationAssitant#2]
替换"."时，“待替换字符串”应该输入的是"\ ."，而不是"\ \ ."，后者不会对文件进行任何更改

**Comment by GWYOG** [comment]
啊...我的锅. 代码中因为还要考虑转义字符的问题所以匹配正则表达式时要输入两个反斜杠，但我忽略了用户在文本框直接输入时不需要考虑转义字符的这个事实

多谢反馈！
