### ISSUE TITLE
“已译词条替换”的第二个模式无法正常使用

### ISSUE THREAD

**Issue by DLslime** [GWYOG/LocalizationAssitant#3]
就是“根据‘英文=中文’格式的文件进行替换”这一项，选定以后按“Go”没有任何反应。

险恶地揣测一下，出现这个BUG似乎与“半成品中文文本Zh_CN.lang”这一项有关？

**Comment by GWYOG** [comment]
抱歉一直没有回复，这段时间我一直忙于毕业论文的答辩没上GitHub.
不知道现在这个问题怎么样了，点击按钮后还是没反应吗？现在这个issue又为什么被关闭了？

**Comment by GWYOG** [comment]
我试了一下确实不能用(汗..)
你说的应该没错, 就是第二个文本框那儿出了问题....
一开始这个功能应该是可以用的, 但某次更新后好像不小心把它搞坏了....我的锅
我抓紧修复下,实在不好意思.
以及多谢反馈.

**Comment by GWYOG** [comment]
已修复, 仓库Release里的jar文件已经换成了新版本1.6.2.

**Comment by DLslime** [comment]
关闭是因为半天没回复，我以为是已知BUG……不过能修就好了~
